# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://cdn.cocoapods.org/'

target 'XHTouchPainter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # UI Helper
  pod 'SnapKit'
  pod 'QMUIKit'
  pod 'Then'
end
